# For the catalyst-helm/pysocha-site helm chart
# See https://github.com/catalystcommunity/chart-pysocha-site

domain: todandlorna.com
sitefilePath: "/site/root"
image:
  # Repository is set via --set in the reactorcide job to use internal registry
  # Internal: 10.16.0.1:5000/private/todpunk/tnl-site
  # External: containers.catalystsquad.com/private/todpunk/tnl-site
  repository: 10.16.0.1:5000/private/todpunk/tnl-site
  # tag will be provided by --set image.tag=...

